### ISSUE TITLE
示例代码首行缩进的解决办法

### ISSUE THREAD

**Issue by xp44mm** [discountry/react#311]
网站`https://react.docschina.org/docs/*.html`示例代码首行缩进了，我将css的margin属性修改后解决了这个问题。
有问题的css
```css
.gatsby-highlight code[class*="gatsby-code-"], .gatsby-highlight pre[class*="gatsby-code-"], .gatsby-highlight pre.prism-code {
    margin: 1rem;
/*其他项目省略*/
}
```
修改后的css
```css
.gatsby-highlight code[class*="gatsby-code-"], .gatsby-highlight pre[class*="gatsby-code-"], .gatsby-highlight pre.prism-code {
    margin: 1rem 0;
/*其他项目省略*/
}
```
